import os from 'node:os';
import path from 'node:path';
import { promises as fs } from 'node:fs';
import { afterEach, describe, expect, it } from 'vitest';
import {
  collectDirectoryTree,
  computeDirTreeHash,
  loadCachedSemantics,
  saveSemanticsCache,
} from '@/analysis/project-semantics-cache.js';
import {
  PROJECT_SEMANTICS_VERSION,
  type ProjectSemantics,
} from '@/types/extensions/project-semantics.js';

async function makeTempProject(): Promise<string> {
  return fs.mkdtemp(path.join(os.tmpdir(), 'archguard-project-semantics-cache-'));
}

function makeSemantics(overrides: Partial<ProjectSemantics> = {}): ProjectSemantics {
  return {
    version: PROJECT_SEMANTICS_VERSION,
    nonProductionPatterns: ['playground'],
    barrelFiles: [],
    additionalTestPatterns: [],
    customAssertionPatterns: [],
    confidence: 0.9,
    _dirTreeHash: 'hash-1',
    _generatedAt: '2026-03-30T00:00:00.000Z',
    ...overrides,
  };
}

const cleanupPaths: string[] = [];

afterEach(async () => {
  await Promise.all(
    cleanupPaths.splice(0).map(async (target) => {
      await fs.rm(target, { recursive: true, force: true });
    })
  );
});

describe('project-semantics-cache', () => {
  it('computeDirTreeHash is stable for the same project', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src', 'core'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, 'tests'), { recursive: true });
    await fs.writeFile(path.join(projectRoot, 'package.json'), '{}');

    const first = await computeDirTreeHash(projectRoot);
    const second = await computeDirTreeHash(projectRoot);

    expect(first).toBe(second);
  });

  it('computeDirTreeHash changes when a directory is added', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src'), { recursive: true });

    const before = await computeDirTreeHash(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'playground'), { recursive: true });
    const after = await computeDirTreeHash(projectRoot);

    expect(after).not.toBe(before);
  });

  it('computeDirTreeHash changes when a config file is added', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src'), { recursive: true });

    const before = await computeDirTreeHash(projectRoot);
    await fs.writeFile(path.join(projectRoot, 'vitest.config.ts'), 'export default {};');
    const after = await computeDirTreeHash(projectRoot);

    expect(after).not.toBe(before);
  });

  it('loadCachedSemantics returns null when cache file is missing', async () => {
    const workDir = await makeTempProject();
    cleanupPaths.push(workDir);

    await expect(loadCachedSemantics(workDir, 'hash-1')).resolves.toBeNull();
  });

  it('loadCachedSemantics returns null when hash mismatches', async () => {
    const workDir = await makeTempProject();
    cleanupPaths.push(workDir);
    await saveSemanticsCache(workDir, makeSemantics({ _dirTreeHash: 'hash-1' }));

    await expect(loadCachedSemantics(workDir, 'hash-2')).resolves.toBeNull();
  });

  it('loadCachedSemantics returns null when version mismatches', async () => {
    const workDir = await makeTempProject();
    cleanupPaths.push(workDir);
    const filePath = path.join(workDir, 'project-semantics.json');
    await fs.writeFile(
      filePath,
      JSON.stringify({
        ...makeSemantics({ _dirTreeHash: 'hash-1' }),
        version: '0.9',
      })
    );

    await expect(loadCachedSemantics(workDir, 'hash-1')).resolves.toBeNull();
  });

  it('loadCachedSemantics returns cached semantics when hash and schema match', async () => {
    const workDir = await makeTempProject();
    cleanupPaths.push(workDir);
    const semantics = makeSemantics({ _dirTreeHash: 'hash-1' });
    await saveSemanticsCache(workDir, semantics);

    await expect(loadCachedSemantics(workDir, 'hash-1')).resolves.toEqual(semantics);
  });

  it('saveSemanticsCache writes valid JSON with the semantics payload', async () => {
    const workDir = await makeTempProject();
    cleanupPaths.push(workDir);
    const semantics = makeSemantics({ _dirTreeHash: 'hash-1' });

    await saveSemanticsCache(workDir, semantics);

    const raw = await fs.readFile(path.join(workDir, 'project-semantics.json'), 'utf8');
    const parsed = JSON.parse(raw) as ProjectSemantics & { _warning?: string };

    expect(parsed.nonProductionPatterns).toEqual(['playground']);
    expect(parsed._warning).toContain('Generated by LLM semantic exploration');
  });

  it('collectDirectoryTree respects the depth limit', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src', 'domain', 'entities', 'deep'), {
      recursive: true,
    });

    const tree = await collectDirectoryTree(projectRoot, 2);

    expect(tree).toContain('src');
    expect(tree).toContain('src/domain');
    expect(tree).not.toContain('src/domain/entities');
  });

  it('collectDirectoryTree truncates output around the 6KB threshold', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);

    for (let index = 0; index < 800; index++) {
      await fs.mkdir(
        path.join(
          projectRoot,
          `very-long-package-name-${index.toString().padStart(4, '0')}-semantic-exploration`
        ),
        {
          recursive: true,
        }
      );
    }

    const tree = await collectDirectoryTree(projectRoot, 3);

    expect(tree).toContain('(truncated, ');
    expect(Buffer.byteLength(tree, 'utf8')).toBeLessThanOrEqual(6200);
  });

  it('collectDirectoryTree excludes noisy generated and dependency directories', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src', 'analysis'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, 'node_modules', 'left-pad'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, 'dist', 'cli'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, '.archguard', 'cache'), { recursive: true });

    const tree = await collectDirectoryTree(projectRoot, 3);

    expect(tree).toContain('src');
    expect(tree).toContain('src/analysis');
    expect(tree).not.toContain('node_modules');
    expect(tree).not.toContain('dist');
    expect(tree).not.toContain('.archguard');
  });

  it('computeDirTreeHash ignores noisy generated and dependency directories', async () => {
    const projectRoot = await makeTempProject();
    cleanupPaths.push(projectRoot);
    await fs.mkdir(path.join(projectRoot, 'src', 'analysis'), { recursive: true });

    const before = await computeDirTreeHash(projectRoot);

    await fs.mkdir(path.join(projectRoot, 'node_modules', 'left-pad'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, 'dist', 'cli'), { recursive: true });
    await fs.mkdir(path.join(projectRoot, '.archguard', 'cache'), { recursive: true });

    const after = await computeDirTreeHash(projectRoot);

    expect(after).toBe(before);
  });
});
