import path from 'node:path';
import crypto from 'node:crypto';
import { promises as fs, type Dirent } from 'node:fs';
import {
  PROJECT_SEMANTICS_VERSION,
  ProjectSemanticsSchema,
  type ProjectSemantics,
} from '@/types/extensions/project-semantics.js';

export const KNOWN_PROJECT_CONFIG_FILES = [
  'jest.config.js',
  'vitest.config.ts',
  'pytest.ini',
  'go.mod',
  'Cargo.toml',
  'CMakeLists.txt',
  'pom.xml',
  'build.gradle',
  'pyproject.toml',
  'package.json',
] as const;

const CACHE_FILE_NAME = 'project-semantics.json';
const TREE_OUTPUT_LIMIT_BYTES = 6 * 1024;
const NOISY_DIRECTORY_NAMES = new Set([
  'node_modules',
  'dist',
  'build',
  'coverage',
  '.archguard',
]);
const ROOT_DIRECTORY_PRIORITY = ['src', 'lib', 'app', 'source', 'tests', 'test'];

function isHiddenDirectory(name: string): boolean {
  return name.startsWith('.');
}

function shouldSkipDirectory(name: string): boolean {
  return isHiddenDirectory(name) || NOISY_DIRECTORY_NAMES.has(name);
}

function compareDirectories(
  left: string,
  right: string,
  relativePrefix: string
): number {
  if (!relativePrefix) {
    const leftPriority = ROOT_DIRECTORY_PRIORITY.indexOf(left);
    const rightPriority = ROOT_DIRECTORY_PRIORITY.indexOf(right);
    if (leftPriority !== -1 || rightPriority !== -1) {
      if (leftPriority === -1) return 1;
      if (rightPriority === -1) return -1;
      if (leftPriority !== rightPriority) return leftPriority - rightPriority;
    }
  }

  return left.localeCompare(right);
}

async function safeReadDir(target: string): Promise<Dirent[]> {
  try {
    return await fs.readdir(target, { withFileTypes: true });
  } catch {
    return [];
  }
}

async function walkDirectories(
  root: string,
  maxDepth: number,
  currentDepth: number,
  relativePrefix: string,
  output: string[]
): Promise<void> {
  if (currentDepth > maxDepth) return;

  const dirPath = relativePrefix ? path.join(root, relativePrefix) : root;
  const entries = await safeReadDir(dirPath);
  const directories = entries
    .filter((entry) => entry.isDirectory() && !shouldSkipDirectory(entry.name))
    .map((entry) => entry.name)
    .sort((left, right) => compareDirectories(left, right, relativePrefix));

  for (const directory of directories) {
    const relativePath = relativePrefix ? path.posix.join(relativePrefix, directory) : directory;
    output.push(relativePath.replace(/\\/g, '/'));
    await walkDirectories(root, maxDepth, currentDepth + 1, relativePath, output);
  }
}

export async function computeDirTreeHash(projectRoot: string): Promise<string> {
  const directories: string[] = [];
  await walkDirectories(projectRoot, 2, 1, '', directories);

  const configFiles = (
    await Promise.all(
      KNOWN_PROJECT_CONFIG_FILES.map(async (fileName) => {
        try {
          await fs.access(path.join(projectRoot, fileName));
          return fileName;
        } catch {
          return null;
        }
      })
    )
  ).filter((fileName) => fileName !== null);

  return crypto
    .createHash('sha256')
    .update(directories.join('\n'))
    .update('\n---\n')
    .update(configFiles.join('\n'))
    .digest('hex');
}

export async function loadCachedSemantics(
  workDir: string,
  currentHash: string
): Promise<ProjectSemantics | null> {
  const filePath = path.join(workDir, CACHE_FILE_NAME);

  try {
    const raw = await fs.readFile(filePath, 'utf8');
    const parsed = ProjectSemanticsSchema.safeParse(JSON.parse(raw));
    if (!parsed.success) {
      return null;
    }
    if (parsed.data.version !== PROJECT_SEMANTICS_VERSION) {
      return null;
    }
    if (parsed.data._dirTreeHash !== currentHash) {
      return null;
    }
    return parsed.data;
  } catch {
    return null;
  }
}

export async function saveSemanticsCache(
  workDir: string,
  semantics: ProjectSemantics
): Promise<void> {
  await fs.mkdir(workDir, { recursive: true });
  await fs.writeFile(
    path.join(workDir, CACHE_FILE_NAME),
    JSON.stringify(
      {
        ...semantics,
        _warning: 'Generated by LLM semantic exploration. Review before relying on it.',
      },
      null,
      2
    )
  );
}

export async function collectDirectoryTree(projectRoot: string, maxDepth: number): Promise<string> {
  const directories: string[] = [];
  await walkDirectories(projectRoot, maxDepth, 1, '', directories);

  if (directories.length === 0) {
    return '(no directories found)';
  }

  let includedCount = directories.length;
  let rendered = directories.join('\n');
  while (Buffer.byteLength(rendered, 'utf8') > TREE_OUTPUT_LIMIT_BYTES && includedCount > 0) {
    includedCount -= 1;
    const remaining = directories.length - includedCount;
    rendered = [
      ...directories.slice(0, includedCount),
      `... (truncated, ${remaining} more directories)`,
    ].join('\n');
  }

  return rendered;
}
